version: "3.7"

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime/:ro
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      DEV_MODE: ${DEV_MODE}
    restart: always
    depends_on:
      - db

  db:
    image: postgres
    hostname: db
    ports:
      - ${DB_OUT_PORT}:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always

  server:
    build:
      context: ./src/nginx
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime/:ro
    ports:
      - ${FRONT_PORT}:80
    restart: always
    depends_on:
      - backend

